name: E Y E   B R A N D   I T
favicon: null
layout_spectrum: 0.25209
typography_spectrum: 0.48228
title: E Y E B R A N D I T
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1215'
    - '#545f63'
    - '#fce778'
    - '#989a52'
    - '#bfbe65'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
