name: eyebrandit
favicon: null
layout_spectrum: 0.27212
typography_spectrum: 0.48228
title: D E S I G N   R E S O U R C E S
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cde8e3'
    - '#775a4a'
    - '#161616'
    - '#c13327'
    - '#cb5e57'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
