name: eyebrandit
favicon: null
layout_spectrum: 0.5804099221713841
typography_spectrum: 0.634195321938023
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5294943619519472
  lightness: 0.6985292870085686
  saturation: 0.4043934824876487
  rhythmicContrast: 0.3155230425763875
purpose: []
