name: eyebrandit
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25
  lightness: 0.6985292870085686
  saturation: 0.6875
  rhythmicContrast: 0.3155230425763875
purpose: []
