name: E Y E   B R A N D   I T
favicon: null
layout_spectrum: 0.25209
typography_spectrum: 0.48228
title: E Y E B R A N D I T
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#efefef'
    - '#403f44'
    - '#9d9d9d'
    - '#dc8c71'
    - '#7b7b7b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
