name: eyebrandit
favicon: null
layout_spectrum: 0.27212
typography_spectrum: 0.48228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e9ea0'
    - '#2e2a27'
    - '#161415'
    - '#46423f'
    - '#7e7d7a'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
